#ifndef DIRECTORYMODEL_GLOBAL_H
#define DIRECTORYMODEL_GLOBAL_H


#include <QtCore/qglobal.h>

#if defined(DIRECTORYMODELLIB_LIBRARY)
#  define DIRECTORYMODELLIBHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIRECTORYMODELLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIRECTORYMODEL_GLOBAL_H
